# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "h2x/Ib5tkrmt0s0A3aw59U83xC3Eta6IvVUWFQvfIXCCCAbF7otCn/pyIsta1uwUgpEiHk5KZelFee+JDCvXJvodENHD7MJzpuSMbpgpiKaz4Hy0YWgcKkmITs0gVZCSgg6rL1kDmQGHDxRxeBuAVKmH3fETNjTQRHU+vjjdJbZZQEeszL4ro/eeaoyXKURWOiK9FrEuDskmvMub91Zew0QP+DETmS6nFt0QhIZogHqOe59oEHJso4C5gypiC4EMhgqYyllQ10l03PRpacpjb2gZ/udKpjR+M82A8lRUFOjxwGS4ngEvQdn0zkvu9wKgQEDezs87ExlsgAQk2UGWkUqHDu1pEWTLVDHfDkErn4BAooXdstcaqrLiFbMr3HDf9TBabN7EnFiKZymZrtvzsg2LUCmUBXxuHcfjc+NX6P09Zfe76NrGPheg1NKZb6JN8KUzu7zE/jFtNNtq7f4386qxTx7fv1Apm6RUwZ2hfIbCqZI8ApgJtCHWr89satQDpn0FIt2zfhW5hXGMcOXDQJI8LAVa7PAGT1gHgemsKBVvVjOkGbNfkTArRC5Gome5l0yz5UH8c5t5vFOoXvoTLb3yOgvEBJ5DdDwAEGz2YrtDAB1BsRhMsHyjvrgV/Vjkz3OhWgaxtPgMj54QzO0b6LhJ6jAPcgPmsL9uVGqPiq8="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
