travis:
  secure:
    BINSTAR_TOKEN: h2x/Ib5tkrmt0s0A3aw59U83xC3Eta6IvVUWFQvfIXCCCAbF7otCn/pyIsta1uwUgpEiHk5KZelFee+JDCvXJvodENHD7MJzpuSMbpgpiKaz4Hy0YWgcKkmITs0gVZCSgg6rL1kDmQGHDxRxeBuAVKmH3fETNjTQRHU+vjjdJbZZQEeszL4ro/eeaoyXKURWOiK9FrEuDskmvMub91Zew0QP+DETmS6nFt0QhIZogHqOe59oEHJso4C5gypiC4EMhgqYyllQ10l03PRpacpjb2gZ/udKpjR+M82A8lRUFOjxwGS4ngEvQdn0zkvu9wKgQEDezs87ExlsgAQk2UGWkUqHDu1pEWTLVDHfDkErn4BAooXdstcaqrLiFbMr3HDf9TBabN7EnFiKZymZrtvzsg2LUCmUBXxuHcfjc+NX6P09Zfe76NrGPheg1NKZb6JN8KUzu7zE/jFtNNtq7f4386qxTx7fv1Apm6RUwZ2hfIbCqZI8ApgJtCHWr89satQDpn0FIt2zfhW5hXGMcOXDQJI8LAVa7PAGT1gHgemsKBVvVjOkGbNfkTArRC5Gome5l0yz5UH8c5t5vFOoXvoTLb3yOgvEBJ5DdDwAEGz2YrtDAB1BsRhMsHyjvrgV/Vjkz3OhWgaxtPgMj54QzO0b6LhJ6jAPcgPmsL9uVGqPiq8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
